name: Checks

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        carbon: ['^2.0', '^3.0']

    name: PHP ${{ matrix.php }} with Carbon ${{ matrix.carbon }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer dependencies with Carbon version ${{ matrix.carbon }}
        run: |
          composer require nesbot/carbon:${{ matrix.carbon }} --no-update
          composer install

      - name: Run tests
        run: composer test

      - name: Run PHPStan
        run: composer phpstan

      - name: Run PHP CS Fixer
        run: composer phpcs
